"use client";
import {useMemo, useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {Filter, MapPinned} from "lucide-react";
import {AppNav} from "@/components/app-nav";
import {StrategicMap} from "@/components/strategic-map";
import {api} from "@/lib/api";
import {useTargetContext} from "@/lib/target-context";
type City={id:number;name:string;x:number;y:number;points:number;is_ghost:boolean;player_id?:number;alliance_id?:number;player_name?:string;alliance_name?:string;relation?:string;target_score?:number;threat_score?:number};type Features={features:{properties:City}[]};type Target={city_id:number;target_score:number};type Threat={player_id:number;score:number};
export default function MapPage(){const map=useQuery({queryKey:["map-cities"],queryFn:()=>api<Features>("/api/map/cities")});const targets=useQuery({queryKey:["map-targets"],queryFn:()=>api<{items:Target[]}>("/api/intelligence/targets?limit=100")});const threats=useQuery({queryKey:["map-threats"],queryFn:()=>api<{items:Threat[]}>("/api/intelligence/threats?limit=100")});const target=useTargetContext(state=>state.target);const setTarget=useTargetContext(state=>state.setTarget);const [mode,setMode]=useState("Tous");const targetScores=useMemo(()=>new Map((targets.data?.items??[]).map(item=>[item.city_id,item.target_score])),[targets.data]);const threatScores=useMemo(()=>new Map((threats.data?.items??[]).map(item=>[item.player_id,item.score])),[threats.data]);const cities=useMemo(()=>(map.data?.features??[]).map(item=>({...item.properties,target_score:targetScores.get(item.properties.id),threat_score:item.properties.player_id?threatScores.get(item.properties.player_id):undefined})),[map.data,targetScores,threatScores]);const visible=useMemo(()=>cities.filter(city=>mode==="Tous"?true:mode==="Mes villes"?city.relation==="SELF":mode==="Alliés"?city.relation==="ALLY":mode==="Cibles"?Boolean(city.target_score):mode==="Menaces"?Boolean(city.threat_score):city.is_ghost),[cities,mode]);return <div className="app-shell"><AppNav/><main className="workspace"><header className="page-heading"><div><p className="eyebrow">GÉOGRAPHIE · RELATIONS · DÉCISION</p><h1>Carte stratégique</h1><p className="lead">Zoomez, déplacez la carte et sélectionnez une ville. Les modes Cibles et Menaces font ressortir les scores réellement calculés.</p></div><span className="read-only"><MapPinned size={15}/>{visible.length} villes visibles</span></header><div className="map-toolbar"><Filter size={16}/>{["Tous","Mes villes","Alliés","Menaces","Cibles","Fantômes"].map(value=><button className={`filter-chip ${mode===value?"active":""}`} onClick={()=>setMode(value)} key={value}>{value}</button>)}</div><div className="map-command"><span>Contexte actif</span><strong>{target?`${target.name}${target.coordinates?` · ${target.coordinates}`:""}`:"Aucune cible sélectionnée"}</strong></div>{map.error?<p className="error">{map.error.message}</p>:<StrategicMap cities={visible} referenceCities={cities} selected={target?.cityId} onSelect={city=>setTarget({cityId:city.id,name:city.name,coordinates:`${city.x}|${city.y}`,source:"carte"})}/>}</main></div>}
