"use client";

import {useQuery} from "@tanstack/react-query";
import {Clock3, Eye, ShieldAlert, Swords} from "lucide-react";
import {api} from "@/lib/api";
import {Skeleton} from "@/components/ui/skeleton";

type Plan={origin:{name:string};distance:number;travel_seconds:number;simulation:{land:{ratio:number};naval:{ratio:number};confidence:number};available_units:Record<string,number>};
type Advice={recommendation:string;confidence:number;target:{last_spy_hours?:number;known_defense?:Record<string,number>};reasons:string[];plans:Plan[];playbook:{stage:string;status:string;reason:string}[]};
const label:Record<string,string>={SCOUT_FIRST:"Espionner d’abord",EVALUATE_ATTACK:"Attaque à évaluer",REINFORCE_OR_AVOID:"Renforcer ou éviter",RECON:"Reconnaissance",NAVAL_CLEAR:"Nettoyage naval",LAND_CLEAR:"Nettoyage terrestre",RE_CLEAN:"Second passage",REVOLT:"Conquête / révolte"};
const duration=(seconds:number)=>seconds>=3600?`${Math.floor(seconds/3600)} h ${Math.round(seconds%3600/60)} min`:`${Math.round(seconds/60)} min`;
export function CombatAdvice({cityId}:{cityId:number}){const query=useQuery({queryKey:["combat-advice",cityId],queryFn:()=>api<Advice>("/api/combat/advice",{method:"POST",body:JSON.stringify({target_city_id:cityId})})});if(query.isLoading)return <section className="panel"><div className="panel-body"><Skeleton className="h-8 w-52"/><Skeleton className="mt-4 h-24 w-full"/></div></section>;if(query.error)return <p className="error">Analyse indisponible : {query.error.message}</p>;const advice=query.data!;const best=advice.plans[0];return <section className="advice-stack"><header className="advice-hero"><div><p className="eyebrow">CONSEILLER D’ATTAQUE · LECTURE SEULE</p><h2>{label[advice.recommendation]??advice.recommendation}</h2><p>{advice.reasons[0]??"Aucune conclusion sans renseignement récent."}</p></div><strong className="confidence"><ShieldAlert size={16}/>{advice.confidence}% confiance</strong></header>{best&&<div className="plan-summary"><article><span>Meilleure origine</span><strong>{best.origin.name}</strong></article><article><span>Distance</span><strong>{best.distance} cases</strong></article><article><span>Durée estimée</span><strong><Clock3 size={15}/>{duration(best.travel_seconds)}</strong></article><article><span>Ratio terrestre</span><strong>{best.simulation.land.ratio}×</strong></article></div>}<div className="advice-grid"><section><p className="eyebrow">PLANS COMPARÉS</p>{advice.plans.length?advice.plans.slice(0,3).map((plan,index)=><article className="plan-row" key={plan.origin.name}><div><strong>{index===0?"Recommandé · ":"Alternative · "}{plan.origin.name}</strong><span>{plan.distance} cases · {duration(plan.travel_seconds)} · sol {plan.simulation.land.ratio}× · naval {plan.simulation.naval.ratio}×</span></div><Swords size={17}/></article>):<p className="empty">Aucune armée personnelle synchronisée.</p>}</section><section><p className="eyebrow">SÉQUENCE CONSEILLÉE</p>{advice.playbook.map(step=><article className={`playbook-step ${step.status}`} key={step.stage}><div><strong>{label[step.stage]??step.stage}</strong><p>{step.reason}</p></div><Eye size={16}/></article>)}</section></div>{advice.target.last_spy_hours!==undefined&&<p className="freshness-note">Renseignement observé il y a {advice.target.last_spy_hours} h. Les paramètres non observés restent exclus du verdict.</p>}</section>}
