"use client";

import Link from "next/link";
import {useState} from "react";
import {Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle} from "@/components/ui/sheet";

type City={id:number;name:string;x:number;y:number;points:number;is_ghost:boolean;player_id?:number|null;alliance_id?:number|null;alliance_name?:string|null;player_name?:string|null;island_x?:number;island_y?:number;distance_to_me?:number;threat_score?:number;target_score?:number;relation?:string};
type Props={cities:City[];referenceCities?:City[];onSelect?:(city:City)=>void;selected?:number};

export function StrategicMap({cities,referenceCities,onSelect,selected}:Props){
  const [zoom,setZoom]=useState(1); const [offset,setOffset]=useState({x:0,y:0}); const [open,setOpen]=useState(false); const [active,setActive]=useState<City>();
  if(!cities.length)return <div className="map-empty">Aucune cité dans ce filtre.</div>;
  const reference=referenceCities?.length?referenceCities:cities; const xs=reference.map(city=>city.x),ys=reference.map(city=>city.y); const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);
  const select=(city:City)=>{setActive(city);setOpen(true);onSelect?.(city)};
  return <><div className="map-frame"><div className="map-controls"><button aria-label="Zoomer" onClick={()=>setZoom(value=>Math.min(3,value+.25))}>+</button><button aria-label="Dézoomer" onClick={()=>setZoom(value=>Math.max(.6,value-.25))}>−</button><button onClick={()=>{setZoom(1);setOffset({x:0,y:0})}}>Recentrer</button></div><div className="strategic-map" onWheel={event=>{event.preventDefault();setZoom(value=>Math.max(.6,Math.min(3,value+(event.deltaY<0?.12:-.12))))}} onPointerDown={event=>{const start={x:event.clientX,y:event.clientY,offset};const move=(pointer:PointerEvent)=>setOffset({x:start.offset.x+pointer.clientX-start.x,y:start.offset.y+pointer.clientY-start.y});const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)}}><div className="map-world" style={{transform:`translate(${offset.x}px,${offset.y}px) scale(${zoom})`}}>{cities.map(city=>{const x=8+84*(city.x-minX)/Math.max(maxX-minX,1),y=8+84*(city.y-minY)/Math.max(maxY-minY,1);const tone=city.is_ghost?"ghost":city.relation?.toLowerCase()??"neutral";return <button title={`${city.name} · ${city.x}|${city.y}`} onClick={()=>select(city)} className={`map-city ${tone} ${selected===city.id?"selected":""}`} style={{left:`${x}%`,top:`${y}%`}} key={city.id}><span className="sr-only">{city.name}</span></button>})}</div><div className="map-scale">Mer Grepolis · coordonnées X / Y fixes</div></div></div><Sheet open={open} onOpenChange={setOpen}><SheetContent><SheetHeader><SheetTitle>{active?.name??"Ville"}</SheetTitle><SheetDescription>{active&&`${active.x}|${active.y} · ${active.points.toLocaleString("fr-FR")} points`}</SheetDescription></SheetHeader>{active&&<CityDetails city={active}/>}</SheetContent></Sheet></>;
}

function CityDetails({city}:{city:City}){return <div className="sheet-city"><dl className="key-values"><div><span>Île</span><strong>{city.island_x!==undefined?`${city.island_x}|${city.island_y}`:"Non renseignée"}</strong></div><div><span>Distance empire</span><strong>{city.distance_to_me!==undefined?`${city.distance_to_me} cases`:"Non renseignée"}</strong></div><div><span>Menace</span><strong>{city.threat_score??"À calculer"}</strong></div><div><span>Cible</span><strong>{city.target_score??"À calculer"}</strong></div></dl><section className="sheet-section"><span>Joueur</span>{city.player_id?<Link className="table-link" href={`/player/${city.player_id}`}>{city.player_name??"Voir le joueur"}</Link>:"Fantôme"}</section><section className="sheet-section"><span>Alliance</span>{city.alliance_id?<Link className="table-link" href={`/alliance/${city.alliance_id}`}>{city.alliance_name??"Voir l’alliance"}</Link>:"Sans alliance"}</section><div className="sheet-actions"><Link className="action-button" href={`/city/${city.id}`}>Voir la ville</Link><Link className="secondary-link" href="/simulator">Analyser une attaque</Link><Link className="secondary-link" href="/planner">Planifier</Link></div></div>}
