import type {CompanionSettings,Snapshot} from "./types/snapshot";
const defaults:CompanionSettings={apiUrl:"http://localhost:18000",pairingToken:"",mode:"PERIODIC",periodMinutes:5};
async function settings(){return {...defaults,...await chrome.storage.local.get(defaults)}}
async function submit(snapshot:Snapshot){const config=await settings();if(!config.pairingToken)return {error:"pairing_required"};const response=await fetch(`${config.apiUrl}/api/personal-state/import`,{method:"POST",headers:{"Content-Type":"application/json","X-GrepoIntel-Pairing":config.pairingToken},body:JSON.stringify(snapshot)});const result=await response.json();if(!response.ok)return {error:result.detail??"import_failed"};await chrome.storage.local.set({lastSync:new Date().toISOString(),lastResult:result});return result;}
async function sync(tabId:number){const capture=await chrome.tabs.sendMessage(tabId,{type:"CAPTURE"});return capture.error?capture:submit(capture.snapshot as Snapshot)}
chrome.runtime.onMessage.addListener((message,sender,respond)=>{if(message?.type==="IMPORT") {submit(message.snapshot as Snapshot).then(respond).catch(error=>respond({error:String(error)}));return true}if(message?.type!=="SYNC"||!sender.tab?.id)return;sync(sender.tab.id).then(respond).catch(error=>respond({error:String(error)}));return true});
chrome.alarms.onAlarm.addListener(async()=>{const config=await settings();if(config.mode!=="PERIODIC")return;for(const tab of await chrome.tabs.query({url:["*://*.grepolis.com/*","*://*.grepolis.fr/*"]}))if(tab.id)await sync(tab.id)});
chrome.storage.onChanged.addListener(async changes=>{if(changes.mode||changes.periodMinutes){const config=await settings();await chrome.alarms.clear("periodic-sync");if(config.mode==="PERIODIC")chrome.alarms.create("periodic-sync",{periodInMinutes:Math.max(5,config.periodMinutes)})}});
async function ensureAutomaticSync(){const stored=await chrome.storage.local.get({mode:undefined,periodMinutes:5,syncPolicyVersion:0});if(stored.syncPolicyVersion<2)await chrome.storage.local.set({mode:"PERIODIC",periodMinutes:5,syncPolicyVersion:2});else if(!stored.mode)await chrome.storage.local.set({mode:"PERIODIC",periodMinutes:5});const config=await settings();await chrome.alarms.clear("periodic-sync");if(config.mode==="PERIODIC")chrome.alarms.create("periodic-sync",{periodInMinutes:Math.max(5,config.periodMinutes)})}
chrome.runtime.onInstalled.addListener(()=>{void ensureAutomaticSync()});chrome.runtime.onStartup.addListener(()=>{void ensureAutomaticSync()});void ensureAutomaticSync();
