"use client";

import {FormEvent, useMemo, useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {Crosshair, Info} from "lucide-react";
import {AppNav} from "@/components/app-nav";
import {CombatAdvice} from "@/components/combat-advice";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {api} from "@/lib/api";
import {useTargetContext} from "@/lib/target-context";

type Unit={id:string;label:string;domain:string;attack:number|null}; type Origin={city_id:number;name:string;coordinates:string;units:Record<string,number>;available:boolean}; type Report={id:number;title:string;city_id?:number;city_name?:string;observed_at?:string}; type Result={land:{attack:number;defense:number;ratio:number;attack_type:string};naval:{attack:number;defense:number;ratio:number};confidence:number;outlook:string;unknown_modifiers:string[]};
export default function SimulatorPage(){const target=useTargetContext(state=>state.target);const catalogue=useQuery({queryKey:["unit-catalogue"],queryFn:()=>api<{items:Unit[]}>("/api/game-data/units")});const context=useQuery({queryKey:["simulator-context"],queryFn:()=>api<{origins:Origin[]}>("/api/manual-intelligence/simulator/context")});const reports=useQuery({queryKey:["spy-reports"],queryFn:()=>api<Report[]>("/api/manual-intelligence/reports")});const [originId,setOriginId]=useState("");const [reportId,setReportId]=useState("");const [wall,setWall]=useState("");const [units,setUnits]=useState<Record<string,number>>({});const [result,setResult]=useState<Result>();const [error,setError]=useState("");
  const selectedReportId=reportId||String(reports.data?.find(item=>item.city_id===target?.cityId)?.id??"");const selectedOriginId=originId||String(context.data?.origins.find(item=>item.available)?.city_id??"");const origin=useMemo(()=>context.data?.origins.find(item=>String(item.city_id)===selectedOriginId),[context.data,selectedOriginId]);const effectiveUnits=Object.keys(units).length?units:origin?.units??{};const unitFields=(catalogue.data?.items??[]).filter(item=>item.attack!==null&&(item.domain!=="naval"||(effectiveUnits[item.id]??0)>0));
  async function simulate(event:FormEvent){event.preventDefault();setError("");setResult(undefined);if(!selectedReportId){setError("Cette cible ne possède pas encore de rapport exploitable. Ajoutez un renseignement avant toute simulation.");return}try{setResult(await api<Result>("/api/manual-intelligence/simulator/attack",{method:"POST",body:JSON.stringify({report_id:Number(selectedReportId),attacker_units:effectiveUnits,wall_level:wall===""?null:Number(wall)})}))}catch(reason){setError(reason instanceof Error?reason.message:"Simulation indisponible")}}
  const targetName=target?.name??"Choisissez une cible depuis Carte ou Cibles";return <div className="app-shell"><AppNav/><main className="workspace"><header className="page-heading"><div><p className="eyebrow">CIBLE → CONSEIL → SIMULATION</p><h1>{targetName}</h1><p className="lead">Les plans automatiques utilisent votre dernier état synchronisé. La simulation avancée ne modifie aucune donnée Grepolis.</p></div></header>{target?<CombatAdvice cityId={target.cityId}/>:<section className="empty-state"><Crosshair size={22}/><h2>Aucune cible active</h2><p>Depuis la carte, une cible ou une fiche ville, utilisez « Analyser l’attaque » pour arriver ici sans ressaisie.</p></section>}
    <Tabs defaultValue="plans" className="simulator-tabs"><TabsList variant="line"><TabsTrigger value="plans">Plans automatiques</TabsTrigger><TabsTrigger value="advanced">Simulation avancée</TabsTrigger></TabsList><TabsContent value="plans"><section className="panel"><div className="panel-body"><p className="result"><Info size={16}/>Le conseiller compare déjà les 2–3 meilleures villes. Passez en simulation avancée seulement pour tester une composition différente.</p></div></section></TabsContent><TabsContent value="advanced"><form className="panel" onSubmit={simulate}><div className="panel-body report-form"><div className="detail-grid"><label className="field">Ville de départ<select value={selectedOriginId} onChange={event=>{const next=event.target.value;setOriginId(next);setUnits(context.data?.origins.find(item=>String(item.city_id)===next)?.units??{})}}>{(context.data?.origins??[]).map(item=><option value={item.city_id} key={item.city_id}>{item.name} · {item.coordinates}{item.available?"":" · non synchronisée"}</option>)}</select></label><label className="field">Renseignement de la cible<select value={selectedReportId} onChange={event=>setReportId(event.target.value)}><option value="">Choisir un rapport</option>{(reports.data??[]).map(item=><option value={item.id} key={item.id}>{item.city_name?`${item.city_name} — `:""}{item.title}</option>)}</select></label><label className="field">Mur observé <small>Vide = inconnu</small><input type="number" min="0" max="25" value={wall} onChange={event=>setWall(event.target.value)} placeholder="Inconnu"/></label></div><section><p className="eyebrow">COMPOSITION À TESTER</p><div className="unit-grid">{unitFields.map(item=><label key={item.id}>{item.label}<input type="number" min="0" value={effectiveUnits[item.id]??0} onChange={event=>setUnits({...effectiveUnits,[item.id]:Number(event.target.value)})}/></label>)}</div></section><button className="action-button" disabled={!origin?.available}>Comparer les forces</button>{error&&<p className="error">{error}</p>}</div></form>{result&&<section className="panel result-card"><div className="panel-body"><h2>Situation {result.outlook}</h2><div className="detail-grid"><Metric label={`Sol · ${result.land.attack_type}`} value={`${result.land.ratio}×`}/><Metric label="Naval" value={`${result.naval.ratio}×`}/><Metric label="Confiance" value={`${result.confidence}%`}/><Metric label="Défense sol connue" value={result.land.defense}/></div><p className="freshness-note">À confirmer : {result.unknown_modifiers.join(" · ")}</p></div></section>}</TabsContent></Tabs></main></div>}
function Metric({label,value}:{label:string;value:string|number}){return <article className="metric"><span className="metric-label">{label}</span><strong className="metric-value">{value}</strong></article>}
