"use client";

import {FormEvent, useMemo, useState} from "react";
import Link from "next/link";
import {useParams} from "next/navigation";
import {useQuery} from "@tanstack/react-query";
import {AppNav} from "@/components/app-nav";
import {DataTable} from "@/components/data-table";
import {StrategicMap} from "@/components/strategic-map";
import {api} from "@/lib/api";

const routes: Record<string, [string, string, string]> = {
  dashboard:["Command center","La situation qui mérite votre attention maintenant.","/api/intelligence/overview"],
  map:["Carte stratégique","Grille Grepolis et détails contextuels.","/api/map/cities"],
  threats:["Menaces","Signaux classés par niveau de pression.","/api/intelligence/threats"],
  targets:["Opportunités","Cibles à évaluer.","/api/intelligence/targets"],
  players:["Joueurs","Répertoire public avec alliances associées.","/api/players?world_id=1&limit=100"],
  alliances:["Alliances","Rapport de forces public.","/api/alliances?world_id=1&limit=100"],
  events:["Événements","Chronologie observée.","/api/events"],
  planner:["Planificateur","Préparer une arrivée sans envoyer d’ordre.","/api/me/cities"],
  simulator:["Simulateur","Rapports manuels et estimation informative.","/api/manual-intelligence/reports"],
  settings:["Réglages","Paramètres publics du monde.","/api/worlds/1"]
};
const rows=(value: unknown): any[] => Array.isArray(value) ? value : (value as any)?.items ?? (value as any)?.features?.map((feature:any)=>({id:feature.properties.city_id,...feature.properties})) ?? [];
const cityLabel=(city:any)=>`${city.name} · ${city.x}|${city.y}`;

export default function SectionPage(){
  const {section}=useParams<{section:string}>();
  const [title,copy,url]=routes[section]??routes.dashboard;
  const query=useQuery({queryKey:[section],queryFn:()=>api<any>(url)});
  const citiesQuery=useQuery({queryKey:["my-cities"],queryFn:()=>api<any[]>("/api/me/cities"),enabled:section==="planner"});
  const data=rows(query.data);
  const [selected,setSelected]=useState<any>(); const [mode,setMode]=useState("Politique"); const [playerSearch,setPlayerSearch]=useState("");
  const [origin,setOrigin]=useState(""); const [target,setTarget]=useState(""); const [arrival,setArrival]=useState(""); const [message,setMessage]=useState("");
  const [report,setReport]=useState(""); const [text,setText]=useState(""); const [units,setUnits]=useState({hoplite:100,sword:0,slinger:0,bireme:0});
  const displayRows=useMemo(()=>section!=="players"?data:data.filter((row:any)=>`${row.name??""} ${row.alliance_name??""}`.toLowerCase().includes(playerSearch.toLowerCase())),[data,playerSearch,section]);
  const visibleCities=useMemo(()=>data.filter((city:any)=>mode==="Cibles"?(city.is_ghost||!city.alliance_id):mode==="Menaces"?!city.is_ghost&&Boolean(city.player_id):true),[data,mode]);
  const resolveCity=(value:string)=>citiesQuery.data?.find((city:any)=>String(city.id)===value||cityLabel(city)===value);
  async function plan(event:FormEvent){event.preventDefault();const originCity=resolveCity(origin),targetCity=resolveCity(target);if(!originCity||!targetCity){setMessage("Choisissez une ville dans chaque liste.");return}try{const result=await api<any>("/api/planner/travel",{method:"POST",body:JSON.stringify({origin_city_id:originCity.id,target_city_id:targetCity.id,unit_speed:1,desired_arrival:arrival||null})});setMessage(`${result.distance} cases · départ : ${result.suggested_departure?new Date(result.suggested_departure).toLocaleString("fr-FR"):"choisissez une arrivée"}`)}catch(error){setMessage(error instanceof Error?error.message:"Calcul indisponible")}}
  async function save(event:FormEvent){event.preventDefault();try{const result=await api<any>("/api/manual-intelligence/reports",{method:"POST",body:JSON.stringify({title:"Rapport manuel",raw_text:text})});setReport(String(result.id));await query.refetch();setMessage("Rapport analysé.")}catch(error){setMessage(error instanceof Error?error.message:"Erreur")}}
  async function simulate(event:FormEvent){event.preventDefault();try{const result=await api<any>("/api/manual-intelligence/simulator/attack",{method:"POST",body:JSON.stringify({report_id:+report,attacker_units:units})});setMessage(`Estimation : ${result.estimated_success_chance}% · ratio ${result.power_ratio??"∞"} · résultat indicatif.`)}catch(error){setMessage(error instanceof Error?error.message:"Choisissez un rapport")}}
  return <div className="app-shell"><AppNav/><main className="workspace"><header className="page-heading"><div><p className="eyebrow">FR183 · INTELLIGENCE LOCALE</p><h1>{title}</h1><p className="lead">{copy}</p></div><span className="read-only"><i className="online-dot"/>À JOUR</span></header>{query.isLoading&&<div className="loading"><i/><i/><i/></div>}{query.error&&<p className="error">{query.error.message}</p>}
    {section==="dashboard"&&<Dashboard data={query.data}/>} {section==="map"&&<MapView cities={data} visibleCities={visibleCities} mode={mode} setMode={setMode} selected={selected} setSelected={setSelected}/>} {section==="planner"&&<Planner cities={citiesQuery.data??[]} origin={origin} target={target} arrival={arrival} setOrigin={setOrigin} setTarget={setTarget} setArrival={setArrival} plan={plan} message={message}/>} {section==="simulator"&&<Simulator reports={data} report={report} setReport={setReport} text={text} setText={setText} units={units} setUnits={setUnits} save={save} simulate={simulate} message={message}/>} {! ["dashboard","map","planner","simulator"].includes(section)&&<section className="panel"><div className="panel-body">{section==="players"&&<label className="field">Rechercher un joueur ou une alliance<input value={playerSearch} onChange={event=>setPlayerSearch(event.target.value)} placeholder="Nom de joueur ou alliance"/></label>}<DataTable rows={displayRows} kind={section==="threats"?"threat":section==="targets"?"target":section==="players"?"player":section==="alliances"?"alliance":"event"}/></div></section>}</main></div>;
}

function MapView({cities,visibleCities,mode,setMode,selected,setSelected}:any){return <><div className="map-toolbar">{["Politique","Menaces","Cibles","Îles"].map(value=><button className={`filter-chip ${mode===value?"active":""}`} onClick={()=>setMode(value)} key={value}>{value}</button>)}</div><div className="map-layout"><StrategicMap cities={visibleCities} referenceCities={cities} selected={selected?.id} onSelect={setSelected}/><aside className="map-detail">{selected?<><p className="eyebrow">CITÉ SÉLECTIONNÉE</p><h2>{selected.name}</h2><p>{selected.points?.toLocaleString("fr-FR")} points · {selected.x}|{selected.y}</p><Link className="action-button" href={`/city/${selected.id}`}>Fiche ville</Link><Link className="secondary-link" href="/planner">Planifier</Link><Link className="secondary-link" href="/simulator">Simuler</Link></>:<p className="empty">Sélectionnez une cité.</p>}</aside></div></>}
function Planner({cities,origin,target,arrival,setOrigin,setTarget,setArrival,plan,message}:any){return <section className="panel"><div className="panel-body"><form className="planner-form" onSubmit={plan}><label className="field">Départ<input list="my-cities" value={origin} onChange={event=>setOrigin(event.target.value)} placeholder="Rechercher une ville"/></label><label className="field">Cible<input list="my-cities" value={target} onChange={event=>setTarget(event.target.value)} placeholder="Ville / coordonnées"/></label><datalist id="my-cities">{cities.map((city:any)=><option value={cityLabel(city)} key={city.id}/>)}</datalist><label className="field">Arrivée<input type="datetime-local" value={arrival} onChange={event=>setArrival(event.target.value)}/></label><button className="action-button">Calculer</button></form>{message&&<p className="result">{message}</p>}</div></section>}
function Simulator({reports,report,setReport,text,setText,units,setUnits,save,simulate,message}:any){return <><section className="panel"><div className="panel-body"><form className="report-form" onSubmit={save}><label>Rapport espionnage<textarea value={text} onChange={event=>setText(event.target.value)} placeholder="Collez le rapport manuel ici"/></label><button className="secondary-button">Analyser</button></form></div></section><section className="panel"><div className="panel-body"><form className="report-form" onSubmit={simulate}><label>Rapport choisi<select value={report} onChange={event=>setReport(event.target.value)}><option value="">Choisir un rapport</option>{reports.map((item:any)=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><div className="unit-grid">{Object.entries(units).map(([unit,value])=><label key={unit}>{unit}<input type="number" min="0" value={value as number} onChange={event=>setUnits({...units,[unit]:+event.target.value})}/></label>)}</div><button className="action-button">Estimer</button></form>{message&&<p className="result">{message}</p>}</div></section></>}
function Dashboard({data}:{data:any}){const threats=data?.threats??[],targets=data?.opportunities??[],recommendations=data?.recommendations??[];return <><section className="command-hero"><div><p className="eyebrow">PRIORITÉ ACTUELLE</p><h2>{recommendations[0]?.title??"Synchronisez votre empire pour une stratégie plus précise."}</h2><p>{recommendations[0]?.message??"Les données publiques sont disponibles ; le Companion apporte ressources et armées."}</p></div><div className="command-stats"><span>● Public</span><span>● Personnel</span><span>{data?.cities?.length??0} villes</span></div></section><div className="dashboard-columns"><section className="panel critical"><header className="panel-head"><h2>Top menaces</h2></header><div className="panel-body">{threats.slice(0,3).map((item:any,index:number)=><article className="signal" key={index}><strong>{item.name}</strong><span>{item.level??"À analyser"}</span></article>)||<p className="empty">Aucune menace forte.</p>}</div></section><section className="panel"><header className="panel-head"><h2>Top opportunités</h2></header><div className="panel-body">{targets.slice(0,3).map((item:any,index:number)=><article className="signal" key={index}><strong>{item.name}</strong><span>Score {item.target_score??"—"}</span></article>)||<p className="empty">Aucune opportunité forte.</p>}</div></section></div></>}
