"use client";

import { FormEvent, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import { Activity, MapPin, ShieldAlert, Target, TrendingUp } from "lucide-react";
import { AppNav } from "@/components/app-nav";
import { DataTable } from "@/components/data-table";
import { GrowthChart } from "@/components/growth-chart";
import { StrategicMap } from "@/components/strategic-map";
import { api } from "@/lib/api";

type Kind = "player" | "alliance" | "city" | "threat" | "target" | "event";
type Config = { title: string; kicker: string; description: string; endpoint: string; kind?: Kind };
const routes: Record<string, Config> = {
  dashboard: { title:"Centre de commandement", kicker:"SITUATION GÉNÉRALE", description:"Synthèse de votre empire, de son évolution et des signaux prioritaires.", endpoint:"/api/dashboard" },
  map: { title:"Carte tactique", kicker:"THÉÂTRE D’OPÉRATION", description:"Distribution des cités connues sur Echidnara. Sélectionnez une cité pour obtenir son renseignement.", endpoint:"/api/cities?world_id=1&limit=250", kind:"city" },
  players: { title:"Répertoire des joueurs", kicker:"RENSEIGNEMENT HUMAIN", description:"Classement, puissance et accès aux fiches d’analyse individuelles.", endpoint:"/api/players?world_id=1&limit=100", kind:"player" },
  alliances: { title:"Ordre des alliances", kicker:"RAPPORT DE FORCES", description:"Les organisations qui structurent le monde et leurs forces déclarées.", endpoint:"/api/alliances?world_id=1&limit=100", kind:"alliance" },
  targets: { title:"Opportunités", kicker:"CIBLAGE STRATÉGIQUE", description:"Cibles évaluées par proximité, état, taille et contexte d’alliance.", endpoint:"/api/analytics/targets", kind:"target" },
  threats: { title:"Veille des menaces", kicker:"ÉVALUATION DU RISQUE", description:"Voisins dont les indicateurs méritent une attention immédiate.", endpoint:"/api/analytics/threats", kind:"threat" },
  events: { title:"Journal d’événements", kicker:"CHRONOLOGIE", description:"Conquêtes et changements détectés entre les instantanés publics.", endpoint:"/api/events", kind:"event" },
  planner: { title:"Planificateur", kicker:"SIMULATION INFORMATIVE", description:"Calculez une fenêtre de départ ; GrepoIntel n’envoie jamais d’ordre au jeu.", endpoint:"/api/me/cities", kind:"city" },
  settings: { title:"Paramètres du monde", kicker:"CONFIGURATION FR183", description:"Règles utilisées par le moteur de calcul. Elles proviennent de l’API.", endpoint:"/api/worlds/1" },
};
const n = (value: unknown) => typeof value === "number" ? value.toLocaleString("fr-FR") : "—";
function Metric({ icon: Icon, label, value, meta, positive }: { icon: typeof Activity; label:string; value:unknown; meta:string; positive?:boolean }) { return <article className="metric"><Icon color={positive ? "#49d49d" : "#55d6ff"} size={18}/><span className="metric-label">{label}</span><strong className={`metric-value ${positive ? "positive" : ""}`}>{n(value)}</strong><span className="metric-meta">{meta}</span></article>; }
function Panel({ title, subtitle, children, action }: { title:string; subtitle?:string; children:React.ReactNode; action?:React.ReactNode }) { return <section className="panel"><header className="panel-head"><div><h2 className="panel-title">{title}</h2>{subtitle && <p className="panel-subtitle">{subtitle}</p>}</div>{action}</header><div className="panel-body">{children}</div></section>; }

export default function Section() {
  const { section } = useParams<{ section: string }>(); const config = routes[section] ?? routes.dashboard;
  const [origin, setOrigin] = useState(""); const [target, setTarget] = useState(""); const [arrival, setArrival] = useState(""); const [result, setResult] = useState("");
  const query = useQuery({ queryKey:["screen", config.endpoint], queryFn:() => api<unknown>(config.endpoint) });
  const cluster = useQuery({ queryKey:["cluster"], queryFn:() => api<{ cohesion_score:number; average_distance:number }>("/api/analytics/cluster"), enabled: section === "dashboard" });
  const rows = useMemo(() => Array.isArray(query.data) ? query.data as Record<string, unknown>[] : query.data && typeof query.data === "object" && "items" in query.data ? (query.data as {items:Record<string,unknown>[]}).items : [], [query.data]);
  const dashboard = query.data as { profile?: { nickname:string; player:Record<string,unknown> }; cities?:Record<string,unknown>[]; alerts?:Record<string,unknown>[] } | undefined;
  async function plan(event:FormEvent) { event.preventDefault(); try { const response = await api<{distance:number; suggested_departure?:string}>("/api/planner/travel", {method:"POST",body:JSON.stringify({origin_city_id:Number(origin),target_city_id:Number(target),unit_speed:1,desired_arrival:arrival || null})}); setResult(`${response.distance} cases · départ estimé : ${response.suggested_departure ? new Date(response.suggested_departure).toLocaleString("fr-FR") : "sélectionnez une arrivée"}`); } catch(error) { setResult(error instanceof Error ? error.message : "Calcul indisponible"); } }
  return <div className="app-shell"><AppNav/><main className="workspace"><header className="page-heading"><div><p className="eyebrow">{config.kicker} · FR183</p><h1>{config.title}</h1><p className="lead">{config.description}</p></div><span className="read-only"><i className="online-dot"/>SYNCHRONISÉ · lecture seule</span></header>
    {query.isLoading && <div className="loading"><i className="loading-block"/><i className="loading-block"/><i className="loading-block"/><i className="loading-block"/></div>}{query.error && <p className="error">{query.error.message}</p>}
    {section === "dashboard" && dashboard?.profile && <><div className="metric-grid"><Metric icon={Activity} label="Points" value={dashboard.profile.player.points} meta={`${n(dashboard.profile.player.growth_24h && (dashboard.profile.player.growth_24h as {points:number}).points)} sur 24 h`} positive/><Metric icon={TrendingUp} label="Classement" value={`#${n(dashboard.profile.player.rank)}`} meta="Position actuelle du monde"/><Metric icon={MapPin} label="Cités" value={dashboard.profile.player.cities_count} meta={`${dashboard.cities?.length ?? 0} positions suivies`}/><Metric icon={ShieldAlert} label="Cohésion" value={cluster.data ? `${cluster.data.cohesion_score}/100` : "—"} meta={cluster.data ? `${cluster.data.average_distance} cases de dispersion` : "Calcul en cours"}/></div><Panel title="Évolution de l’empire" subtitle="Progression de points basée sur les snapshots publics."><GrowthChart history={Array.isArray(dashboard.profile.player.history) ? dashboard.profile.player.history as {timestamp:string;points:number}[] : []}/></Panel><div className="split-grid"><Panel title="Positions alliées" subtitle="Vos cités associées au profil local." action={<span className="read-only"><MapPin size={13}/> {dashboard.cities?.length ?? 0} cités</span>}><DataTable rows={dashboard.cities ?? []} kind="city"/></Panel><Panel title="Signaux prioritaires" subtitle="Alertes calculées, avec facteurs consultables."><>{dashboard.alerts?.length ? dashboard.alerts.map((alert,index)=><div className="alert" key={index}><i className="alert-marker"/><div><strong>{String(alert.title)}</strong><span>{String(alert.detail)}</span></div></div>) : <p className="empty">Aucun signal fort dans les données disponibles.</p>}</></Panel></div></>}
    {section === "map" && <><Panel title="Carte opérationnelle" subtitle="Bleu : cité occupée · violet : fantôme. Cliquez sur un point pour ouvrir la fiche."><div className="map-toolbar"><span className="filter-chip active">Toutes les cités</span><span className="filter-chip">Fantômes</span><span className="filter-chip">Sans alliance</span><span className="filter-chip">Proches de moi</span></div><div style={{height:14}}/><StrategicMap cities={rows as {id:number;name:string;x:number;y:number;points:number;is_ghost:boolean;player_id?:number|null}[]}/></Panel><Panel title="Répertoire cartographique" subtitle={`${rows.length} cités chargées dans cette fenêtre.`}><DataTable rows={rows} kind="city"/></Panel></>}
    {section === "planner" && <Panel title="Calcul de trajet" subtitle="Simulation de déplacement : aucune commande ne quitte GrepoIntel."><form className="planner-form" onSubmit={plan}><div className="field"><label>Ville de départ</label><input value={origin} onChange={e=>setOrigin(e.target.value)} placeholder="ID de ville" required/></div><div className="field"><label>Ville cible</label><input value={target} onChange={e=>setTarget(e.target.value)} placeholder="ID de ville" required/></div><div className="field"><label>Arrivée souhaitée</label><input type="datetime-local" value={arrival} onChange={e=>setArrival(e.target.value)}/></div><button className="action-button">Calculer l’itinéraire</button></form>{result && <p className="result">{result}</p>}<div style={{height:18}}/><DataTable rows={rows} kind="city"/></Panel>}
    {section === "settings" && Boolean(query.data) && <Panel title="Règles actives" subtitle="Réglages retournés par le backend pour Echidnara."><div className="metric-grid">{Object.entries(query.data as Record<string,unknown>).filter(([,value])=>["string","number","boolean"].includes(typeof value)).slice(0,8).map(([key,value])=><article className="metric" key={key}><span className="metric-label">{key.replaceAll("_"," ")}</span><strong className="metric-value">{String(value)}</strong></article>)}</div></Panel>}
    {config.kind && !["city"].includes(section) && section !== "planner" && <Panel title={config.title} subtitle={`${rows.length} résultats chargés depuis l’API.`}><DataTable rows={rows} kind={config.kind}/></Panel>}
  </main></div>;
}
