"use client";

import {useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {AppNav} from "@/components/app-nav";
import {api} from "@/lib/api";

type City={city_id:number;name:string;role:string;recommended_role:string;population:Record<string,number>;resources:Record<string,number>;buildings:Record<string,number>;researches:Record<string,boolean>;units:Record<string,Record<string,number>>;god?:string;hero?:Record<string,unknown>;freshness:{status:string;age_minutes:number};next_best_actions:{action:string;reason:string}[]};
type Empire={available:boolean;cities:City[]};
const labels:Record<string,string>={main:"Sénat",farm:"Ferme",storage:"Entrepôt",barracks:"Caserne",academy:"Académie",market:"Marché",lumber:"Scierie",stoner:"Carrière",ironer:"Mine d’argent",docks:"Port",wall:"Mur",NAVAL_DEFENSE:"Défense navale",LAND_OFFENSE:"Offensive terrestre",ECONOMY:"Économie",MIXED:"Mixte",UNDEFINED:"À définir"};
const sourceLinks=[{title:"Support Grepolis — premiers pas",href:"https://support.innogames.com/kb/Grepolis/en_DK/3239/First-Steps"},{title:"Guide communautaire — progression première ville",href:"https://grepolisgrepolis.wordpress.com/grepolis-guides-2/beginners-guide-starting-out/"}];

export default function Empire(){const query=useQuery({queryKey:["empire"],queryFn:()=>api<Empire>("/api/micro/empire")});const [chosen,setChosen]=useState(0);const [tab,setTab]=useState("Synthèse");const city=query.data?.cities[chosen];return <div className="app-shell"><AppNav/><main className="workspace"><header className="page-heading"><div><p className="eyebrow">MON EMPIRE · ÉTAT PERSONNEL</p><h1>Organisation des villes</h1><p className="lead">Une lecture locale par ville, avec un plan de construction traçable vers des guides Grepolis.</p></div></header>{!query.data?.available?<section className="empty-state"><h2>État personnel requis</h2><p>Le Companion synchronisera ici les ressources, l’armée et les bâtiments.</p></section>:<div className="empire-layout"><aside className="city-list"><p className="eyebrow">{query.data.cities.length} VILLES</p>{query.data.cities.map((item,index)=><button className={index===chosen?"selected":""} onClick={()=>setChosen(index)} key={item.city_id}><strong>{item.name}</strong><span>{labels[item.recommended_role]??item.recommended_role} · {item.freshness.status}</span></button>)}</aside>{city&&<section className="city-detail"><header className="city-title"><div><p className="eyebrow">VILLE SÉLECTIONNÉE</p><h2>{city.name}</h2><p>{labels[city.role]??city.role} → {labels[city.recommended_role]??city.recommended_role}</p></div><span className={`freshness ${city.freshness.status.toLowerCase()}`}>{city.freshness.status}</span></header><div className="detail-tabs">{["Synthèse","Armée","Bâtiments","Héros & dieu","Roadmap","Recommandations"].map(value=><button className={tab===value?"active":""} onClick={()=>setTab(value)} key={value}>{value}</button>)}</div>{tab==="Synthèse"&&<div className="detail-grid"><Metric label="Population libre" value={city.population.free??"Inconnue"}/><Metric label="Bois" value={city.resources.wood??"Inconnu"}/><Metric label="Pierre" value={city.resources.stone??"Inconnue"}/><Metric label="Argent" value={city.resources.silver??"Inconnu"}/><Metric label="Faveur" value={city.resources.favor??"Inconnue"}/><Metric label="Capacité" value={city.resources.storage_capacity??"Inconnue"}/></div>}{tab==="Armée"&&<Values title="Unités présentes" data={city.units.home??{}}/>}{tab==="Bâtiments"&&<div className="detail-grid"><Values title="Bâtiments" data={city.buildings}/><Values title="Recherches" data={city.researches}/></div>}{tab==="Héros & dieu"&&<div className="detail-grid"><Metric label="Héros assigné" value={String(city.hero?.name??"Aucun détecté")}/><Metric label="Dieu" value={city.god??"Non renseigné"}/></div>}{tab==="Roadmap"&&<BuildingRoadmap city={city}/>} {tab==="Recommandations"&&<div>{city.next_best_actions.map(action=><article className="recommendation" key={action.action}><div><strong>{action.action}</strong><p>{action.reason}</p></div></article>)||<p className="empty">Aucune action.</p>}</div>}</section>}</div>}</main></div>}
function Metric({label,value}:{label:string;value:string|number}){return <article className="metric"><span className="metric-label">{label}</span><strong className="metric-value">{typeof value==="number"?value.toLocaleString("fr-FR"):value}</strong></article>}
function Values({title,data}:{title?:string;data:Record<string,unknown>}){const entries=Object.entries(data);return <section className="key-values">{title&&<h3>{title}</h3>}{entries.length?entries.map(([key,value])=><div key={key}><span>{labels[key]??key.replaceAll("_"," ")}</span><strong>{typeof value==="boolean"?(value?"Oui":"Non"):String(value)}</strong></div>):<p className="empty">Aucune donnée relevée.</p>}</section>}
function BuildingRoadmap({city}:{city:City}){const target=city.recommended_role==="LAND_OFFENSE"?{main:15,farm:25,storage:13,academy:13,barracks:10,market:5}:{main:15,farm:25,storage:13,academy:13,docks:10,market:5};const steps=Object.entries(target).filter(([building,level])=>(city.buildings[building]??0)<level).map(([building,level])=>({building,from:city.buildings[building]??0,to:level})).slice(0,5);return <section className="roadmap"><p className="lead">Parcours {labels[city.recommended_role]??city.recommended_role}, adapté aux niveaux reçus. Il suit les jalons récurrents des guides débutants : population et stockage, puis académie et capacité militaire.</p>{steps.length?steps.map((step,index)=><article className="recommendation" key={step.building}><div><span className="eyebrow">ÉTAPE {index+1}</span><strong>{labels[step.building]??step.building} : niveau {step.from} → {step.to}</strong><p>{step.building==="farm"?"Libère la population nécessaire aux bâtiments et unités.":step.building==="storage"?"Évite de perdre les ressources produites ou reçues.":step.building==="academy"?"Ouvre les recherches de progression et de spécialisation.":"Prépare la capacité militaire et les prérequis de la ville."}</p></div></article>):<p className="result">Les jalons initiaux du parcours sont atteints.</p>}<p className="eyebrow">SOURCES DE STRATÉGIE</p>{sourceLinks.map(source=><a className="table-link" href={source.href} target="_blank" rel="noreferrer" key={source.href}>{source.title} ↗</a>)}</section>}
