"use client";

import {useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {useRouter} from "next/navigation";
import {Crosshair, Eye, ShieldAlert} from "lucide-react";
import {AppNav} from "@/components/app-nav";
import {Badge} from "@/components/ui/badge";
import {api} from "@/lib/api";
import {useTargetContext} from "@/lib/target-context";
type Threat={player_id:number;name:string;alliance?:{name:string};score:number;level:string;nearest_distance:number;nearby_city_count:number;reasons:{message:string}[]};type Player={cities:{id:number;name:string;x:number;y:number}[]};
export default function ThreatsPage(){const query=useQuery({queryKey:["threats"],queryFn:()=>api<{items:Threat[]}>("/api/intelligence/threats?limit=30")});const router=useRouter();const setTarget=useTargetContext(state=>state.setTarget);const [loading,setLoading]=useState<number>();async function analyse(item:Threat){setLoading(item.player_id);try{const player=await api<Player>(`/api/players/${item.player_id}`);const city=player.cities[0];if(!city)return;setTarget({cityId:city.id,name:city.name,coordinates:`${city.x}|${city.y}`,source:"menaces"});router.push("/simulator")}finally{setLoading(undefined)}}return <div className="app-shell"><AppNav/><main className="workspace"><header className="page-heading"><div><p className="eyebrow">RENSEIGNEMENT · PRESSION</p><h1>Menaces à surveiller</h1><p className="lead">Le score combine proximité, activité publique et contexte d’alliance. Une analyse choisit une ville connue du joueur, sans ressaisie.</p></div></header>{query.error&&<p className="error">{query.error.message}</p>}<div className="threat-list">{query.data?.items.map(item=><article className="threat-card" key={item.player_id}><div className="threat-score"><strong>{item.score}</strong><span>score</span></div><div className="threat-copy"><p className="eyebrow">{item.level}</p><h2>{item.name}</h2><p>{item.alliance?.name??"Sans alliance"} · {item.nearest_distance} cases · {item.nearby_city_count} ville(s) proche(s)</p><span>{item.reasons[0]?.message??"Signal à confirmer"}</span></div><Badge variant={item.score>=70?"destructive":"outline"}><ShieldAlert size={13}/>{item.level}</Badge><div className="threat-actions"><button className="action-button" disabled={loading===item.player_id} onClick={()=>analyse(item)}><Crosshair size={16}/>{loading===item.player_id?"Ouverture…":"Analyser"}</button><button className="secondary-button" onClick={()=>router.push(`/player/${item.player_id}`)}><Eye size={15}/>Fiche</button></div></article>)}</div></main></div>}
