import type {Snapshot,TownState,Json} from "../../types/snapshot";
import {sanitize} from "../../sanitize";
type AnyRecord=Record<string,any>;
const record=(v:any):AnyRecord=>v&&typeof v==="object"?v:{};
const values=(v:any):any[]=>Array.isArray(v)?v:Object.values(record(v));
const get=(object:any,...keys:string[])=>keys.map(key=>record(object)[key]).find(value=>value!==undefined);
const numberMap=(source:any):Record<string,number>=>Object.fromEntries(Object.entries(record(source)).filter(([,v])=>typeof v==="number").map(([k,v])=>[k,v as number]));
/** Read-only adapter: probes already-loaded collections only. It never fetches, clicks or mutates page state. */
export class GrepolisClientAdapter {
  constructor(private readonly page:AnyRecord){}
  private townCollection(){const iTowns=record(this.page.ITowns);return get(iTowns,"towns")??get(this.page,"towns","Towns")??get(record(this.page.Game),"towns");}
  player(){const game=record(this.page.Game);const data=record(this.page.GameData);return record(get(game,"player")??get(data,"player")??get(this.page,"player"));}
  world(){const game=record(this.page.Game);const data=record(this.page.GameData);const raw=String(get(game,"world_id","world")??get(data,"world_id","world")??"");const fromHost=globalThis.location?.hostname.match(/([a-z]{2}\d+)/i)?.[1];return (fromHost??raw).toUpperCase();}
  town(raw:any):TownState|null { const town=record(raw); const id=get(town,"id","town_id","townId"); if(id===undefined)return null; const resources=numberMap(get(town,"resources","resource_storage")); const population=numberMap(get(town,"population","population_state")); const buildings=numberMap(get(town,"buildings","building_levels")); const researches=Object.fromEntries(Object.entries(record(get(town,"researches","researches_available"))).filter(([,v])=>typeof v==="boolean")); const unitsRaw=record(get(town,"units","unit_counts")); const units=Object.keys(unitsRaw).some(key=>typeof unitsRaw[key]==="number")?{home:numberMap(unitsRaw)}:Object.fromEntries(Object.entries(unitsRaw).map(([key,value])=>[key,numberMap(value)])); return {external_city_id:String(id),name:String(get(town,"name")??""),x:Number(get(town,"x","island_x")??0),y:Number(get(town,"y","island_y")??0),island_x:Number(get(town,"island_x")??0),island_y:Number(get(town,"island_y")??0),resources,population,buildings,researches,units,queues:record(get(town,"queues","build_queue")) as Record<string,Json[]>,god:typeof get(town,"god") === "string"?get(town,"god"):undefined,hero:record(get(town,"hero","assigned_hero")) as Record<string,Json>}; }
  capture():Snapshot {const diagnostics:Snapshot["diagnostics"]={Player:"FAILED",Towns:"FAILED",Resources:"PARTIAL",Population:"PARTIAL",Buildings:"PARTIAL",Research:"PARTIAL",Units:"PARTIAL",Heroes:"PARTIAL",Queues:"PARTIAL"};const player=this.player();const towns=values(this.townCollection()).map(item=>this.town(item)).filter((item):item is TownState=>item!==null);if(Object.keys(player).length)diagnostics.Player="OK";if(towns.length){diagnostics.Towns="OK";if(towns.some(t=>Object.keys(t.resources??{}).length))diagnostics.Resources="OK";if(towns.some(t=>Object.keys(t.population??{}).length))diagnostics.Population="OK";if(towns.some(t=>Object.keys(t.buildings??{}).length))diagnostics.Buildings="OK";if(towns.some(t=>Object.keys(t.researches??{}).length))diagnostics.Research="OK";if(towns.some(t=>Object.keys(t.units??{}).length))diagnostics.Units="OK";}const playerName=String(get(player,"name","player_name")??"");return sanitize({schema:"grepointel-personal-state",version:1,world:this.world(),player:playerName,captured_at:new Date().toISOString(),cities:towns,heroes:values(get(this.page,"heroes", "Heroes")) as Json[],diagnostics,client_version:typeof this.page.GameVersion==="string"?this.page.GameVersion:undefined}) as Snapshot;}
}
