import type {Snapshot,TownState,Json} from "../../types/snapshot.js";
import {sanitize} from "../../sanitize.js";
type R=Record<string,any>; type D={path:string;type:string;keys:string[];methods:string[];count?:number};
const rec=(v:any):R=>v&&typeof v==="object"?v:{};
export function callSafeGetter(model:any,key:string){try{return typeof model?.[key]==="function"?model[key]():undefined}catch{return undefined}}
export function readField(model:any,...keys:string[]){for(const key of keys){if(model?.[key]!==undefined&&typeof model[key]!=="function")return model[key];const directGetter=callSafeGetter(model,key);if(directGetter!==undefined)return directGetter;try{const value=model?.get?.(key);if(value!==undefined)return value}catch{}if(rec(model?.attributes)[key]!==undefined)return rec(model.attributes)[key];const value=callSafeGetter(model,`get${key[0].toUpperCase()}${key.slice(1)}`);if(value!==undefined)return value}return undefined}
export function readModel(model:any):R{return {...rec(model?.attributes),...rec(callSafeGetter(model,"toJSON")),...rec(model)}}
export function readCollection(collection:any):any[]{if(Array.isArray(collection))return collection;if(Array.isArray(collection?.models))return collection.models;const json=callSafeGetter(collection,"toJSON");if(Array.isArray(json))return json;return Object.values(rec(collection)).filter(v=>v&&typeof v==="object"&&("attributes" in v||"id" in v))}
const nums=(v:any):Record<string,number>=>Object.fromEntries(Object.entries(readModel(v)).filter(([,x])=>typeof x==="number") as [string,number][]);const bools=(v:any):Record<string,boolean>=>Object.fromEntries(Object.entries(readModel(v)).filter(([,x])=>typeof x==="boolean") as [string,boolean][]);
const describe=(path:string,v:any):D=>({path,type:Array.isArray(v)?"array":typeof v,keys:Object.keys(readModel(v)).filter(k=>!/cookie|password|csrf|token|session|auth/i.test(k)).slice(0,40),methods:Object.keys(rec(v)).filter(k=>typeof rec(v)[k]==="function"&&["get","toJSON","getCollections","getModels"].includes(k)),count:readCollection(v).length||undefined});
/** Passive only: direct property → Backbone get() → attributes → public getter → toJSON(). */
export class GrepolisClientAdapter {private used:R={};private found:D[]=[];constructor(private page:R){} private seen(path:string,v:any){if(v!=null)this.found.push(describe(path,v));return v}
 private collections(){const mm=this.seen("MM",this.page.MM);return this.seen("MM.getCollections",callSafeGetter(mm,"getCollections")??readField(mm,"collections"))}
 private find(names:string[],kind:string){for(const [path,root] of [["ITowns",this.page.ITowns],["MM.getCollections",this.collections()],["Game",this.page.Game],["GameData",this.page.GameData],["window",this.page]] as [string,any][])for(const name of names){const value=readField(root,name);if(readCollection(value).length){this.used[kind]=`${path}.${name}`;return this.seen(`${path}.${name}`,value)}}}
 private player(){for(const [path,root] of [["Game",this.page.Game],["GameData",this.page.GameData],["MM",this.page.MM],["window",this.page]] as [string,any][])for(const key of ["player","Player","current_player"]){const value=readField(root,key);if(Object.keys(readModel(value)).length){this.used.Player=`${path}.${key}`;return value}}}
 private playerName(player:any){for(const [path,root] of [["Player",player],["Game",this.page.Game],["GameData",this.page.GameData],["ITowns",this.page.ITowns],["window",this.page]] as [string,any][])for(const key of ["name","player_name","playerName","username","user_name"]){const value=readField(root,key);if(typeof value==="string"&&value.trim()){this.used.Player=this.used.Player??`${path}.${key}`;return value.trim()}}return ""}
 private town(raw:any):TownState|null{const id=readField(raw,"id","town_id","townId");if(id===undefined)return null;const resources=nums(readField(raw,"resources","resource_storage","resources_storage","resourceStorage"));for(const key of ["wood","stone","silver","iron"]){const value=readField(raw,key);if(typeof value==="number")resources[key==="iron"?"silver":key]=value}const favor=readField(raw,"favor","god_favor");if(typeof favor==="number")resources.favor=favor;const u=readModel(readField(raw,"units","unit_counts","units_home","units_at_home","available_units","unitCounts"));const units=Object.values(u).some(x=>typeof x==="number")?{home:nums(u)}:Object.fromEntries(Object.entries(u).map(([k,v])=>[k,nums(v)]));const god=readField(raw,"god","god_name");const rawQueues=readModel(readField(raw,"queues","build_queue","orders"));const queues=Object.fromEntries(Object.entries(rawQueues).filter(([,value])=>Array.isArray(value))) as Record<string,Json[]>;const rawPopulation=readField(raw,"population","population_state","available_population","populationState");const population=typeof rawPopulation==="number"?{free:rawPopulation}:nums(rawPopulation);return {external_city_id:String(id),name:String(readField(raw,"name")??""),x:Number(readField(raw,"x","town_x","island_x")??0),y:Number(readField(raw,"y","town_y","island_y")??0),island_x:Number(readField(raw,"island_x")??0),island_y:Number(readField(raw,"island_y")??0),resources,population,buildings:nums(readField(raw,"buildings","building_levels","building_data","buildingLevels")),researches:bools(readField(raw,"researches","researches_available","researches_data","researchesData")),units,queues,god:typeof god==="string"?god:undefined,hero:readModel(readField(raw,"hero","assigned_hero","hero_data")) as Record<string,Json>}}
 capture():Snapshot{const diagnostics:Snapshot["diagnostics"]={Player:"FAILED",Towns:"FAILED",Resources:"PARTIAL",Population:"PARTIAL",Buildings:"PARTIAL",Research:"PARTIAL",Units:"PARTIAL",Heroes:"PARTIAL",Queues:"PARTIAL"};const player=this.player();const playerName=this.playerName(player);const towns=readCollection(this.find(["towns","Town","Towns","TownCollection"],"Towns")).map(x=>this.town(x)).filter((x):x is TownState=>!!x);if(playerName)diagnostics.Player="OK";if(towns.length){diagnostics.Towns="OK";([['Resources','resources'],['Population','population'],['Buildings','buildings'],['Research','researches'],['Units','units'],['Queues','queues']] as const).forEach(([d,k])=>{if(towns.some(t=>Object.keys(t[k]??{}).length))diagnostics[d]="OK"})}const heroes=readCollection(this.find(["heroes","Hero","Heroes"] ,"Heroes"));if(heroes.length)diagnostics.Heroes="OK";const raw=String(readField(this.page.Game,"world_id","world")??readField(this.page.GameData,"world_id","world")??"");const host=globalThis.location?.hostname.match(/([a-z]{2}\d+)/i)?.[1];return sanitize({schema:"grepointel-personal-state",version:1,world:(host??raw).toUpperCase(),player:playerName,captured_at:new Date().toISOString(),cities:towns,heroes:heroes.map(readModel) as Json[],diagnostics,runtime_diagnostic:{extractors:diagnostics,paths:this.used,collections:this.found}}) as Snapshot}}
